In [80]:
import numpy as np
import scipy.io as sio
import open3d as o3d

# Load the .mat file
datapath = "xyz5.mat"
mat = sio.loadmat(datapath)

# grid_size = (24, 24, 24)
# grid_size = (32, 32, 32)
# grid_size = (48, 48, 48)
grid_size = (64, 64, 64)

In [81]:
npxyz = np.asarray(mat['xyz'])
print(type(npxyz))
print(npxyz.shape)
print(npxyz)

<class 'numpy.ndarray'>
(41935, 3)
[[   2   -1    1]
 [   9   -1    1]
 [  10   -1    1]
 ...
 [ 314 -139  357]
 [ 317 -139  357]
 [ 318 -139  357]]


In [82]:
npcolor = np.asarray(mat['color'])
print(type(npcolor))
print(npcolor.shape)
print(npcolor)


<class 'numpy.ndarray'>
(41935, 3)
[[255 255   0]
 [255 255   0]
 [255 255   0]
 ...
 [255   0   0]
 [255   0   0]
 [255   0   0]]


In [83]:
# Assuming the point cloud data is stored in a variable named 'pointCloud'
points = mat['xyz']
color = mat['color']

# Create an Open3D point cloud object
point_cloud = o3d.geometry.PointCloud()

# Assign colors to the point cloud object
# Open3D expects color values to be in the range [0, 1]
color = color / 255.0
point_cloud.colors = o3d.utility.Vector3dVector(color)

# Assign points to the point cloud object
point_cloud.points = o3d.utility.Vector3dVector(points)

# fit to unit cube. 
point_cloud.scale( (grid_size[0] - 1) / (np.max(point_cloud.get_max_bound() - point_cloud.get_min_bound())),
          center=point_cloud.get_center())

# Visualize the point cloud
# o3d.visualization.draw_geometries([point_cloud])
print(point_cloud.get_max_bound())
print(point_cloud.get_min_bound())

[258.15198569 -19.41922785 130.82539454]
[195.15198569 -35.97922785  88.10539454]


In [92]:
# Create a voxel grid from the point cloud with a voxel_size of 0.01
voxel_grid=o3d.geometry.VoxelGrid.create_from_point_cloud(point_cloud,voxel_size=0.05)

# print(voxel_grid.check_if_included(point_cloud.points))
# voxel_grid.get_center()
# voxel_grid.dimension()
# voxel_grid.get_geometry_type()
# voxel_grid.get_voxel([0,0,0])
# np.asarray(voxel_grid.get_voxel_bounding_points([0,0,0]))
# voxel_grid.get_voxel_center_coordinate([0,0,0])
# voxel_grid.has_voxels()
# voxel_grid.is_empty()
# voxel_grid.voxel_size
# voxel_grid.has_colors()
# len(voxel_grid.get_voxels())

True

In [85]:

min_bound = voxel_grid.get_min_bound()
max_bound = voxel_grid.get_max_bound()
voxel_size = (max_bound - min_bound) / np.array(grid_size)
print(voxel_size)
print(min_bound, max_bound)

[0.98515625 0.259375   0.66796875]
[195.12698569 -36.00422785  88.08039454] [258.17698569 -19.40422785 130.83039454]


In [86]:

occupancy_grid = np.zeros(grid_size, dtype=bool)
for voxel in voxel_grid.get_voxels():
    # print(voxel.grid_index)
    index = voxel.grid_index.astype(int)
    if np.all(index >= 0) and np.all(index < grid_size):
        occupancy_grid[tuple(index)] = True
        # print(index)


In [87]:
voxel_centers = []
grid_size = occupancy_grid.shape
for x in range(grid_size[0]):
    for y in range(grid_size[1]):
        for z in range(grid_size[2]):
            if occupancy_grid[x, y, z]:
                voxel_centers.append([x, y, z])
voxel_centers = np.array(voxel_centers)

print((voxel_centers.shape))
print((occupancy_grid.shape))

(0,)
(64, 64, 64)


In [88]:
# # Create a VoxelGrid from the voxel centers
# if len(voxel_centers) > 0:
#     voxel_centers = o3d.utility.Vector3dVector(voxel_centers)
#     new_voxel_grid = o3d.geometry.VoxelGrid.create_from_points(voxel_centers, voxel_size)
print(type(voxel_size))

<class 'numpy.ndarray'>


In [89]:
if len(voxel_centers) > 0:
    point_cloud2 = o3d.geometry.PointCloud()
    point_cloud2.points = o3d.utility.Vector3dVector(voxel_centers)
    
    # Create a VoxelGrid from the PointCloud
    new_voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(point_cloud2, voxel_size=0.7)

    print(len(new_voxel_grid.get_voxels()))


In [90]:
# Initialize a visualizer object
vis = o3d.visualization.Visualizer()
# Create a window, name it and scale it
vis.create_window(window_name='dummy Visualize', width=1400, height=900)

# Add the voxel grid to the visualizer
vis.add_geometry(voxel_grid)

# We run the visualizater
vis.run()
# Once the visualizer is closed destroy the window and clean up
vis.destroy_window()

In [16]:
import numpy as np

a = np.load("volumetric_data\\car\\30\\test\\car_000000073_4.npy")

np.savetxt('car_000000073_4.dat',a)

ValueError: Expected 1D or 2D array, got 3D array instead